export const items = [
  {
    id: 1,
    title: "همبرگر مخصوص",
    price: 10000,
    count: 0,
    image: "src/images/Berguer.jpg",
  },
  {
    id: 2,
    title: "همبرگر معمولی",
    price: 8000,
    count: 0,
    image: "src/images/Berguer.jpg",
  },
  {
    id: 3,
    title: " همبرگر مخصوص قارچ و پنیر",
    price: 20000,
    count: 0,
    image: "src/images/Berguer.jpg",
  },
  {
    id: 4,
    title: "همبرگر معمولی با قارچ و پنیر",
    price: 10000,
    count: 0,
    image: "src/images/Berguer.jpg",
  },
  {
    id: 5,
    title: "سیب زمینی سرخ کرده",
    price: 10000,
    count: 0,
    image: "src/images/french_fries.png",
  },
  {
    id: 6,
    title: "سیب زمینی سرخ کرده ویژه",
    price: 25000,
    count: 0,
    image: "src/images/french_fries.png",
  },
  {
    id: 7,
    title: "نوشابه",
    price: 5000,
    count: 0,
    image: "src/images/soda.png",
  },
  {
    id: 8,
    title: "نوشابه رژیمی",
    price: 6000,
    count: 0,
    image: "src/images/soda.png",
  },
  {
    id: 9,
    title: "سالاد سزار",
    price: 25000,
    count: 0,
    image: "src/images/salad.png",
  },
  {
    id: 10,
    title: "سالاد فصل",
    price: 8000,
    count: 0,
    image: "src/images/salad.png",
  },
];
